apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: default
  labels:
    app: weblog
    type: database
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      imagePullPolicy: Never
      resources:
        requests:
          ephemeral-storage: "1Gi"
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root_password
        - name: MYSQL_DATABASE
          value: todo_db
      volumeMounts:
        - name: storage
          mountPath: "/data/storage"
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-claim
